Default: &defaults
  database: aah.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: aah_test.sqlite3
  <<: *defaults

Staging:
  database: aah_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: aah_production.sqlite3
  poolsize: 100
  <<: *defaults
